### ISSUE TITLE
Use of tei:desc with tei:relation elements

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriaca-data#1151]
What use do we have for tei:desc as child of tei:relation?

We aren't currently doing much with most of these. They aren't rendered in the HTML. See person/51 in master: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/51.xml#L607. Notice that this record doesn't include a `<note type="disambiguation">`. This data only gets rendered in HTML in the LOD box on the right side of the page.

Person/160 (in master), however, includes both a `<note type="disambiguation">` and a tei:relation[formerly name but now @type='disambiguation']/tei:desc. The note gets rendered in HTML with other notes and the desc does not get rendered even though the tei:relation data does get rendered in the LOD box.

We have (rightly, I believe) decided that maintaining the data in two places as in person/160 is not something we want to do. When we have a prose rendering of a relationship like this we should nest it under tei:relation.

This raises an issue about where we want to require tei:relation/tei:desc and where we want to allow it even if we don't require it. 

Addressing this issue also requires us to decide what we want to render into HTML. If we don't render everything, how will we designate what we want to render?

- Personal relationships
     - In SPEAR, we include prose renderings: https://spear-prosop.org/aggregate/person/13.html
- Place relationships
     - We currently have a generic tei:desc as child of tei:relation that we don't render. See https://syriaca.org/person/160. Do we need this tei:desc? We could go without.
- Disambiguation relationships
     - We currently have a generic tei:desc that we don't render. See https://syriaca.org/person/51. Do we need to include this.
     - On the other hand, in the draft repo (2023.02.21_schemaWork), we have moved the `<note type="disambiguation">` down into the tei:relation/tei:desc: https://github.com/srophe/srophe-app-data/blob/2023.02.21_schemaWork/data/persons/tei/160.xml#L303. I think we would want to render this as a discursive note along with the other notes.
- Pseudonymity relationships
     - I think we will want to render these in prose in the HTML. But I have questions about where each of these tei:relation elements should reside. Do we want all three relationships in all three of the relevant records (the known person, the actual author of the pseudonymous text, and the pseudo/composite author; see [diagram](https://docs.google.com/drawings/d/18EJGIpkhit037qX6JcHeMibYx3SnP-wHiz4fS173CiM/edit))

**Comment by dlschwartz** [comment]
To start the discussion, I propose that we always allow tei:desc as child of tei:relation but that the app only render the tei:desc among the notes when the encoder adds an optional @type="note" attribute.

**Comment by dlschwartz** [comment]
Here are some examples of different kinds of relationships and how the data about them appears in the TEI.

# Large quantity of values in a single relationship
For relationships with a lot of values and no real need to render data into a prose note, we can include a tei:desc that we wouldn't need to display as a note in HTML. It would display in HTML only in the LOD box. See this example from person/51.
```
<relation type="place" ref="http://syriaca.org/keyword/has-literary-relation-to-place" source="#bib51-2" active="#person-51" 
   passive="http://syriaca.org/place/586 http://syriaca.org/place/1468 http://syriaca.org/place/180 http://syriaca.org/place/118
       http://syriaca.org/place/174 http://syriaca.org/place/11 http://syriaca.org/place/1469 http://syriaca.org/place/343
       http://syriaca.org/place/9 http://syriaca.org/place/10 http://syriaca.org/place/196 http://syriaca.org/place/75
       http://syriaca.org/place/1457 http://syriaca.org/place/151 http://syriaca.org/place/663 http://syriaca.org/place/1470
       http://syriaca.org/place/1471 http://syriaca.org/place/40 http://syriaca.org/place/122 http://syriaca.org/place/1472
       http://syriaca.org/place/215 http://syriaca.org/place/1473 http://syriaca.org/place/1474 http://syriaca.org/place/1475
       http://syriaca.org/place/233 http://syriaca.org/place/130 http://syriaca.org/place/65 http://syriaca.org/place/185
       http://syriaca.org/place/195 http://syriaca.org/place/1476 http://syriaca.org/place/146 http://syriaca.org/place/211
       http://syriaca.org/place/219 http://syriaca.org/place/1477 http://syriaca.org/place/60 http://syriaca.org/place/351
       http://syriaca.org/place/89">
       <desc xml:lang="en">This author has a literary connection to places.</desc>
</relation>
```
The downside to this is that we lose a meaning rdfs:label for each of these triples associating Severus with a place. The alternative would be to break this out into 37 tei:relation elements with a tei:desc in each that lists Severus by name/URI and the place by name/URI. Either way, we wouldn't want to include this in the list of notes in HTML.

# Single value pair but no need for an HTML note
For relationships with a single value we still might not need to render a tei:desc into an HTML note. See this example, also from person/51. BTW, in order to produce a meaningful rdfs:label this tei:desc ought to be rewritten to include `<persName ref="http://syriaca.org/person/51>Severus</persName>"` instead of leaving him unnamed. Either way, it is probably sufficient to have this data displayed in HTML only in the LOD box.
```
<relation type="disambiguation" ref="http://syriaca.org/keyword/distinct-entities" mutual="http://syriaca.org/person/51 http://syriaca.org/person/164">
   <desc xml:lang="en">Not the same as <persName ref="http://syriaca.org/person/164">Severos</persName>.</desc>
</relation>
```

# Relationship tei:desc contains important discursive note
For cases where we want the note to display in HTML, we add a `@type="note"` to the tei:desc. Winona would use this to render this tei:desc among the other tei:note elements.
```
<relation type="disambiguation" ref="http://syriaca.org/keyword/distinct-entities" mutual="http://syriaca.org/person/160 http://syriaca.org/person/444" resp="http://syriaca.org">
   <desc xml:lang="en" type="note">
      It is unclear why Barsoum asserts that this apparently
      West Syrian <persName ref="http://syriaca.org/person/160">Denha</persName> 
      is the same as an East Syrian <persName ref="http://syriaca.org/person/444">Denha</persName> who wrote a
      commentary on the Psalms and several other works. His placement of this
      West Syrian Denha in the 9th century does not have any apparent basis
      besides this identification, and should also be held loosely.</desc>
</relation>
```

**Comment by davidamichelson** [comment]
Editorial Decisions:

When a relation has ref="http://syriaca.org/keyword/has-literary-relation-to-place" we are just going to ignore this data. Someone in the future may research it and improve it, but for now we will neither visualize it in HTML nor serialize it to RDF. This data came from hand reading and mark up of Barsoum. It is found only in 9 records. See person/51 as an example.

When a relation has ref="http://syriaca.org/keyword/has-relation-to-place" we are going to delete all of this data from all records (it was generated internally from the record, so nothing is lost by deleting these relations anyway). In the future, this will be generated at the time of RDF serialization.

**Comment by davidamichelson** [comment]
Regarding: Single value pair but no need for an HTML note

In these cases we should add a @type of note  on relation type="disambiguation"/desc [not(@type="note)]

**Comment by dlschwartz** [comment]
The above commit resolves this issue.
