### ISSUE TITLE
tei:desc with pseudonymity relationships

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriaca-data#1163]
See error messages in person/601 and person/3501. I think we want to give some thought to the text nodes of the tei:desc elements in these (and similar) tei:relation elements.

**Comment by dlschwartz** [comment]
https://docs.google.com/drawings/d/18EJGIpkhit037qX6JcHeMibYx3SnP-wHiz4fS173CiM/edit

**Comment by davidamichelson** [comment]
In the anonymous record, the desc should read: "This anonymous author is associated with tradition of X." Where X=Pseudo-Macarius or whatever.

**Comment by davidamichelson** [comment]
For ref="http://syriaca.org/keyword/shares-attribution-with" "This author shares attribution with X".

**Comment by dlschwartz** [comment]
In cases where there is an anonymous author, a pseudonymous author, and a known person, we will use the following

For the anonymous author of a work:
```
<relation type="pseudonymity" ref="http://www.w3.org/2004/02/skos/core#broader" active="http://syriaca.org/person/601" passive="http://syriaca.org/person/3501" resp="http://syriaca.org">
    <desc type="note" xml:lang="en">This anonymous author is also identified as <persName ref="http://syriaca.org/person/3501">Pseudo-Macarius</persName>.</desc>
</relation>
```

For the known author with works false attributed to them:
```
<relation type="pseudonymity" ref="http://syriaca.org/keyword/shares-attribution-with" mutual="http://syriaca.org/person/3501 http://syriaca.org/person/856" resp="http://syriaca.org">
    <desc type="note" xml:lang="en">This author shares attribution with <persName ref="http://syriaca.org/person/3501">Pseudo-Macarius</persName>.</desc>
</relation>
```

For the pseudonymous author associated with a known author:
```
<relation type="pseudonymity" ref="http://syriaca.org/keyword/shares-attribution-with" mutual="http://syriaca.org/person/3501 http://syriaca.org/person/856" resp="http://syriaca.org">
    <desc type="note" xml:lang="en">This pseudonymous author shares attribution with <persName ref="http://syriaca.org/person/856">Macarius</persName>.</desc>
</relation>
```

**Comment by dlschwartz** [comment]
The above comment and the above commit close this issue.
