### ISSUE TITLE
CBSS Zotero record fields not included in TEI transformation

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca-data#1178]
The following fields are not currently included in the Zotero -> TEI pipeline. I've given initial thoughts on how they should render, but we should discuss.

Zotero API return example JSON record to use: https://api.zotero.org/groups/4861694/items/2T6FWIUY?format=json&include=bib,data&style=chicago-note-bibliography

# Tags

In the `tags` array of the JSON return. Short term, we want to bring these in similar to how biblia-arabica does it. [Example TEI](https://biblia-arabica.com/bibl/VC847CSA.tei) Longer term we will work to integrate this with the 

Example:
```
<relation active="http://syriaca.org/cbss/2T6FWIUY" ref="dc:subject" type="subject">
  <desc>Acts of Thomas</desc>
</relation>
```
- `@active` is the URI of the bibl record
- `@ref` is "dc:subject" by default
- `@type` is "subject" by default
- `/desc` is the string from the JSON return

Ideally the keywords will be facetable in browse and advanced search (cf. related app issue: https://github.com/srophe/syriaca/issues/113)

----

# Extra Field

The extra field has some key: value pairs we want, and some we can ignore. For now, we want to make sure we bring in the `deprecated` key:value pairs.

I am not sure if we want to do the full deprecation-redirect system that we use for other entities? These could simply be imported as:

```
<idno type="deprecated">http://syriaca.org/bibl/988</idno>
<idno type="deprecated"> http://syriaca.org/bibl/1908</idno>
<idno type="deprecated">https://zotero.org/groups/392292/items/FNE38ZRP</idno>
```
- `idno` used by default
- `@type` coming from the extra field key
- `/text()` coming from the extra field value for each "deprecated" key

These URIs could be used, especially the syriaca.org ones, for managing redirects and forwarding.

----

Note: there may be additional fields to bring in, but more discussion is needed. The above list should let us replicate the functionality of the previous version of CBSS.
- Additional extra field key:value pairs are subject to review
- Zotero's `itemType` field (cf. https://github.com/srophe/syriaca/issues/117)

**Comment by wlpotter** [comment]
@wsalesky For the record/item type, here is what I found in terms of values:

```
book
journalArticle
bookSection
thesis
note
encyclopediaArticle
attachment
webpage
```

I think these are all fine to use as the value of `//biblStruct/@type` in the TEI.

It does look like the Zotero data dump includes the notes (itemType of "note") and attachments (itemType of "attachment"). Does the transform ignore these so we do not create XML records for the notes or attachments?

**Comment by wsalesky** [comment]
@wlpotter New version of the data is up, if you would like to take a look at it.

**Comment by wlpotter** [comment]
@wsalesky The data here looks good. Do we want to pull this branch into development?

**Comment by wlpotter** [comment]
FYI @wsalesky pull request into development created for this data update

**Comment by wlpotter** [comment]
Closing this as the new data was merged to development branch. See #1181 for pushing data to the dev server
