### ISSUE TITLE
Push CBSS data to Syriaca dev server

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca-data#1181]
@wsalesky I believe the CBSS data was added to the [development branch](https://github.com/srophe/syriaca-data/tree/development/data/bibl/tei) but was not yet deployed to the dev server.

I believe this should be the URL of a record on dev, once data is pushed: https://dev-syriacaorg.vuexistapps.us/cbss/ERZZH57E. It corresponds to: https://www.zotero.org/groups/4861694/items/ERZZH57E

**Comment by wsalesky** [comment]
@wlpotter I pushed the new data to the server, please take a look. I will be working on the search/browse/facets next.

**Comment by wlpotter** [comment]
Thanks for pushing these -- data looks to be up on dev server
