### ISSUE TITLE
Bibl records missing from CBSS

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca-data#1186]
@wsalesky I'm opening this issue for tracking down why we only ended up with 1,008 records from CBSS after the zotero to tei transform. There should be 27,545 items.

We do have all the JSON data that you downloaded via API -- I have a version that you sent via dropbox or box that has everything.

I think the TEI files were added with [this commit](https://github.com/srophe/syriaca-data/commit/0af6df63e7a42335fc27b6cd0310ccdef923661b), and it seems there are only the 1,008 records there. I think maybe we just need to re-run the transform on the JSON and make sure all the records get added?

Maybe on Tuesday we can talk through how to run the transform? (I'm assuming it can run on a local eXist instance?)

**Comment by wsalesky** [comment]
Yes, lets figure it out on Tuesday.

**Comment by wsalesky** [comment]
@wlpotter Can you send me a zotero id for a note (I lost it after our meeting yesterday!) thanks

**Comment by wsalesky** [comment]
Also, here is a version without the parentItem filter:
https://github.com/srophe/syriaca-data/tree/cbssDataDump6-19-24

It has 27800 records

**Comment by wlpotter** [comment]
Here is an id for a note: DPTBW6NN (cf. https://api.zotero.org/groups/4861694/items/DPTBW6NN).

**Comment by wsalesky** [comment]
See: https://github.com/srophe/syriaca-data/pull/1190

**Comment by wlpotter** [comment]
@wsalesky This looks like all of them! But we want to pull into development right?

**Comment by wsalesky** [comment]
@wlpotter Yes, sorry about that!
